version: 2
updates:
  - package-ecosystem: npm
    commit-message:
      prefix: "fix(deps)"
    update-lockfile: true
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      time: "12:00"
      timezone: EST
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    open-pull-requests-limit: 10
    reviewers:
    - fhlavac
    - nicolethoen
    - dlabaj

  - package-ecosystem: npm
    commit-message:
      prefix: "fix(deps)"
    update-lockfile: true
    directory: "/packages/module"
    schedule:
      interval: weekly
      day: tuesday
      time: "12:00"
      timezone: EST
    schedule:
      interval: weekly
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    open-pull-requests-limit: 10
    reviewers:
    - fhlavac
    - nicolethoen
    - dlabaj
